// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxh2nqXr-VAuv6BgNzOlnewMSg1zMVSag',
    appId: '1:991176670931:web:d7bc5931d32fe013401e26',
    messagingSenderId: '991176670931',
    projectId: 'okrdatabase-92b3e',
    authDomain: 'okrdatabase-92b3e.firebaseapp.com',
    storageBucket: 'okrdatabase-92b3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxezznR57Ol8AGqvuCaty_YgZujLNciWk',
    appId: '1:991176670931:android:6316a228554403ac401e26',
    messagingSenderId: '991176670931',
    projectId: 'okrdatabase-92b3e',
    storageBucket: 'okrdatabase-92b3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2dMyZm_q-MLuUuwLIBlFR1KfQ1LTioCk',
    appId: '1:991176670931:ios:ec9d3043daa69e52401e26',
    messagingSenderId: '991176670931',
    projectId: 'okrdatabase-92b3e',
    storageBucket: 'okrdatabase-92b3e.appspot.com',
    iosClientId:
        '991176670931-kgcgt7bsabft8mssg2iv50uotk35ghde.apps.googleusercontent.com',
    iosBundleId: 'com.example.myokr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2dMyZm_q-MLuUuwLIBlFR1KfQ1LTioCk',
    appId: '1:991176670931:ios:ec9d3043daa69e52401e26',
    messagingSenderId: '991176670931',
    projectId: 'okrdatabase-92b3e',
    storageBucket: 'okrdatabase-92b3e.appspot.com',
    iosClientId:
        '991176670931-kgcgt7bsabft8mssg2iv50uotk35ghde.apps.googleusercontent.com',
    iosBundleId: 'com.example.myokr',
  );
}
